version: '3.7'

services:

  db:
    image: postgres:14.8-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes: 
      - frontend_volume:/usr/src/frontend
    depends_on:
      - django
    
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: 
      - ./.env
    working_dir: "/usr/src/backend/project"
    command: sh -c "python /usr/src/backend/project/manage.py migrate && python -m uvicorn core.asgi:application --host 0.0.0.0 --port 8000"
    volumes:
      - .:/usr/src
    ports:
      - 8000:8000
    depends_on:
      - db


volumes:
  postgres_data:
  frontend_volume: 